import fs from 'node:fs';
import path from 'node:path';
import { gameTitleKey, games } from '../config/catalog';

export interface ShowcaseItem {
    title: string;
    description: string;
    href: string;
    image: string;
    tags?: string[];
    category?: string;
    homepage?: boolean;
    publishDate?: string;
    author?: string;
}

export function homeGameSlides(items: ShowcaseItem[]) {
    const catalogKeys = new Set(games.map((game) => gameTitleKey(game.title)));
    const extra = items.filter(
        (item) =>
            (item.category === 'game' || item.tags?.includes('game')) &&
            !catalogKeys.has(gameTitleKey(item.title))
    );

    return [
        ...games.map((game) => ({
            title: game.title,
            tagline: game.tagline,
            href: game.href,
            image: cardAsset(game.image),
        })),
        ...extra.map((item) => ({
            title: item.title.replace(/:.*$/, ''),
            tagline: item.description,
            href: playgroundHref(item.href),
            image: cardAsset(item.image),
        })),
    ];
}

export function interactiveArticles(items: ShowcaseItem[]): ShowcaseItem[] {
    return items.filter((item) => item.category === 'article');
}

export function publicAsset(assetPath: string) {
    if (!assetPath) return assetPath;
    return assetPath.startsWith("/") ? assetPath : `/${assetPath}`;
}

/** Card-sized WebP next to the original screenshot, generated by `npm run optimize-carousel-thumbs`. */
export function cardAsset(assetPath: string) {
    const pub = publicAsset(assetPath);
    if (!pub) return pub;
    const card = pub.replace(/\.(png|jpe?g|webp)$/i, '-card.webp');
    const onDisk = path.join(process.cwd(), 'public', card.replace(/^\//, ''));
    return fs.existsSync(onDisk) ? card : pub;
}

export function homepageShowcases(items: ShowcaseItem[]): ShowcaseItem[] {
    return items.filter((item) => item.homepage !== false);
}

export function showcasesInCategory(items: ShowcaseItem[], category: string): ShowcaseItem[] {
    return homepageShowcases(items).filter((item) => item.category === category);
}

export function showcaseSlug(href: string) {
    const normalized = href.replace(/\\/g, "/").replace(/^\//, "");
    const parts = normalized.split("/");
    if (parts[0] === "html_showcase" && parts[1]) return parts[1];
    throw new Error(`Cannot derive playground slug from ${href}`);
}

export function playgroundHref(href: string) {
    return `/playground/${showcaseSlug(href)}`;
}
